name: Integration test

on:
  pull_request:

jobs:
  integration-tests:
    name: Integration test
    # TODO: Switch back to using staging env runners.
    runs-on: ["self-hosted", "large"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
      - name: Run Integration tests
        run: |
          tox -e integration -- \
            --keep-models \
            --path ${{secrets.E2E_TESTING_REPO}} \
            --token ${{secrets.E2E_TESTING_TOKEN}}
