name: Integration test

on:
  pull_request:

jobs:
  integration-tests:
    name: Integration test
    # TODO: Switch back to using staging env runners.
    runs-on: ["self-hosted", "test-runner"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          # TODO: juju version should be a workflow input.
          juju-channel: 3.0/stable
          provider: lxd
      - name: Run Integration tests
        run: |
          tox -e integration -- \
            --keep-models \
            --path ${{secrets.E2E_TESTING_REPO}} \
            --token ${{secrets.E2E_TESTING_TOKEN}}
      # TODO: Debug only
      - name: Wait 6 hours
        run: sleep 6h
