name: integration-tests

on:
  pull_request:

jobs:
  integration-tests-microstack:
    name: Integration test using microstack
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      juju-channel: 3.2/stable
      pre-run-script: scripts/setup-microstack.sh
      provider: microk8s
      channel: 1.26-strict/stable
      microk8s-addons: "dns ingress hostpath-storage"
      test-tox-env: integration-juju3.2
      modules: '["test_openstack"]'
      self-hosted-runner: true
      self-hosted-runner-label: two-xlarge
