name: Integration test

on:
  pull_request:

jobs:
  integration-test:
    name: Integration test
    # TODO: Change to main branch
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@feat/integration-test-secret-arguments
    secrets: inherit
    with:
      juju-channel: 3.1/stable
      provider: lxd
