name: Integration test

on:
  pull_request:

jobs:
  integration-tests:
    name: Integration test
    runs-on: [self-hosted, test-runner]
    steps:
      - uses: actions/checkout@v3
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          # TODO: juju version should be a workflow input.
          juju-channel: 3.1/stable
          provider: lxd
      - name: Enable br_netfilter
        run: sudo modprobe br_netfilter
      - name: Run Integration tests
        run: |
          tox -e integration -- \
            --keep-models \
            --path ${{secrets.E2E_TESTING_REPO}} \
            --token ${{secrets.E2E_TESTING_TOKEN}} \
            --http-proxy $http_proxy \
            --https-proxy $https_proxy \
            --no-proxy $no_proxy
