name: integration-tests

on:
  #pull_request:
  workflow_dispatch:

jobs:
  # test option values defined at test/conftest.py are passed on via repository secret
  # INTEGRATION_TEST_ARGS to operator-workflows automatically.
  integration-tests-juju2:
    name: Integration test with juju 2.9
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@self-hosted-runner-integration-test
    secrets: inherit
    with:
      juju-channel: 2.9/stable
      pre-run-script: scripts/pre-integration-test.sh
      provider: lxd
      test-tox-env: integration-juju2.9
      modules: '["test_charm_fork_repo", "test_charm_no_runner", "test_charm_scheduled_events", "test_charm_one_runner", "test_charm_metrics", "test_self_hosted_runner", "test_charm_with_proxy"]'
      self-hosted-runner: true
      self-hosted-runner-label: "edge"
  integration-tests-juju3:
    name: Integration test with juju 3.1
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@self-hosted-runner-integration-test
    secrets: inherit
    with:
      juju-channel: 3.1/stable
      pre-run-script: scripts/pre-integration-test.sh
      provider: lxd
      test-tox-env: integration-juju3.1
      modules: '["test_charm_fork_repo", "test_charm_no_runner", "test_charm_scheduled_events", "test_charm_one_runner", "test_charm_metrics", "test_self_hosted_runner", "test_charm_with_proxy"]'
      self-hosted-runner: true
      self-hosted-runner-label: "edge"
