name: Manual test

on:
  # push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: [self-hosted, test]
    steps:
      - run: echo $DOCKERHUB_MIRROR
      - run: docker run hello-world
      # - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs >> rustup.sh
      # - run: sh rustup.sh -y
      # - run: $HOME/.cargo/bin/cargo install ripgrep
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     limit-access-to-actor: true
