name: Manual test

on:
  # pull_request:
  workflow_dispatch:

jobs:
  test-proxy:
    name: test proxy
    runs-on: [self-hosted, xlarge]
    steps:
      - name: curl
        run: curl -vvv https://s3.amazonaws.com/data-charms-testing?list-type=2&prefix=mysql%2F&delimiter=%2F&encoding-type=url
      - name: Install requests
        if: ${{ success() || failure() }}
        run: python3 -m pip install requests
      - name: Make HTTP request with Python
        if: ${{ success() || failure() }}
        run: python3 -c "import logging;logging.basicConfig(level=logging.DEBUG);import requests;resp=requests.get('https://s3.amazonaws.com/data-charms-testing?list-type=2&prefix=mysql%2F&delimiter=%2F&encoding-type=url', proxies={'https':'http://squid.internal:3128'});print(resp.content)"
