name: Manual test

on:
  # push:
  pull_request:
  workflow_dispatch:

jobs:
  github-test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo test
        run: echo hello
      - name: Disk usage
        run: df -h
  # self-host-test:
  #   name: self-hosted test
  #   runs-on: [self-hosted, edge, jammy]
  #   steps:
  #     - run: echo hello
  #     - run: df -h
      # - uses: actions/checkout@v4.1.1
      # - uses: canonical/setup-lxd@v0.1.1
      # - name: Pack charm
      #   run: |
      #     sudo snap install charmcraft --classic --channel latest/stable
      #     charmcraft pack -v
      # - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs >> rustup.sh
      # - run: sh rustup.sh -y
      # - run: $HOME/.cargo/bin/cargo install ripgrep
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     limit-access-to-actor: true
