name: Manual test

on:
  # TODO: Re-enable
  pull_request:
  # workflow_dispatch:

jobs:
  integration-tests-microstack:
    name: Integration test using microstack
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      juju-channel: 3.1/stable
      # LXD not used. Set to `lxd` to prevent the lengthy microk8s installation by default.
      provider: lxd
      test-tox-env: integration-juju3.1
      extra-arguments: '--openstack'
      modules: '["test_openstack_runner"]'
      self-hosted-runner: true
      self-hosted-runner-label: xlarge
      tmate-debug: true
      tmate-timeout: 2400
