name: Manual test

on:
  # push:
  pull_request:
  workflow_dispatch:

jobs:
  # github-test:
    # runs-on: ubuntu-latest
    # steps:
    #   - run: sudo apt-get update
    #   - run: sudo apt install -y fio
    #   - name: seq write
    #     run: sudo fio --name=write_throughput --directory=/ --numjobs=4 --size=3G --time_based --runtime=60s --ramp_time=2s --ioengine=libaio --direct=1 --verify=0 --bs=1M --iodepth=64 --rw=write --group_reporting=1 --iodepth_batch_submit=64 --iodepth_batch_complete_max=64
    #   - run: sudo rm -f /write* /read*
    #   - name: rand write
    #     run: sudo fio --name=write_iops --directory=/ --numjobs=4 --size=3G --time_based --runtime=60s --ramp_time=2s --ioengine=libaio --direct=1 --verify=0 --bs=4k --iodepth=256 --rw=randwrite --group_reporting=1 --iodepth_batch_submit=256 --iodepth_batch_complete_max=256
    #   - run: sudo rm -f /write* /read*
    #   - name: seq read
    #     run: sudo fio --name=write_throughput --directory=/ --numjobs=4 --size=3G --time_based --runtime=60s --ramp_time=2s --ioengine=libaio --direct=1 --verify=0 --bs=1M --iodepth=64 --rw=read --group_reporting=1 --iodepth_batch_submit=64 --iodepth_batch_complete_max=64
    #   - run: sudo rm -f /write* /read*
    #   - name: rand read
    #     run: sudo fio --name=write_iops --directory=/ --numjobs=4 --size=3G --time_based --runtime=60s --ramp_time=2s --ioengine=libaio --direct=1 --verify=0 --bs=4k --iodepth=256 --rw=randread --group_reporting=1 --iodepth_batch_submit=256 --iodepth_batch_complete_max=256
    #   - run: sudo rm -f /write* /read*
  self-host-test:
    name: self-hosted test
    runs-on: [self-hosted, medium]
    steps:
      - run: lscpu
      - run: echo hello
      - run: df -h
      - run: echo $DOCKERHUB_MIRROR
      - name: Install microk8s
        run: sudo snap install microk8s --classic
  # - uses: actions/checkout@v4.1.1
  # - uses: canonical/setup-lxd@v0.1.1
  # - name: Pack charm
  #   run: |
  #     sudo snap install charmcraft --classic --channel latest/stable
  #     charmcraft pack -v
  # - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs >> rustup.sh
  # - run: sh rustup.sh -y
  # - run: $HOME/.cargo/bin/cargo install ripgrep
  # - name: Setup tmate session
  #   uses: mxschmitt/action-tmate@v3
  #   with:
  #     limit-access-to-actor: true
