name: Manual test

on:
  # push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: [self-hosted, large]
    steps:
      - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
      - run: cargo install ripgrep
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     limit-access-to-actor: true
