name: Manual test

on:
  # TODO: Re-enable
  pull_request:
  # workflow_dispatch:

jobs:
  integration-tests-microstack:
    name: Integration test using microstack
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      juju-channel: 3.2/stable
      test-tox-env: integration-juju3.2
      extra-arguments: '--openstack'
      modules: '["test_openstack_runner"]'
      self-hosted-runner: true
      self-hosted-runner-label: xlarge
      tmate-debug: true
      tmate-timeout: 2400
