name: Manual test

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: [self-hosted, small]
    steps:
      - name: Echo hello world
        run: echo "hello world"
