name: Manual test

on:
  pull_request:
  workflow_dispatch:

jobs:
  test-proxy:
    name: test proxy
    strategy:
      matrix:
        num: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    runs-on: [self-hosted, xlarge]
    steps:
      - name: Echo
        runs: echo "Hello number ${{ matrix.num }}"
