name: Manual test

on:
  # push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: [self-hosted, test]
    steps:
      - name: env
        run: echo $DOCKERHUB_MIRROR
      - name: test
        run: echo "hello world"
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     limit-access-to-actor: true
