name: Manual test

on:
  # push:
  pull_request:
  workflow_dispatch:

jobs:
  publish-docs:
    name: Publish docs
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          ref: main
      - name: Search for docs folder
        id: docs-exist
        run: echo "docs_exist=$([[ -d docs ]] && echo 'True' || echo 'False')" >> $GITHUB_OUTPUT
      - name: Publish documentation
        if: steps.docs-exist.outputs.docs_exist == 'True'
        uses: canonical/discourse-gatekeeper@stable
        id: publishDocumentation
        with:
          discourse_host: discourse.charmhub.io
          discourse_api_username: ${{ secrets.DISCOURSE_API_USERNAME }}
          discourse_api_key: ${{ secrets.DISCOURSE_API_KEY }}
          dry_run: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Show index page
        if: steps.docs-exist.outputs.docs_exist == 'True'
        run: echo '${{ steps.publishDocumentation.outputs.index_url }}'
  # github-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Echo test
  #       run: echo hello
  #     - name: Disk usage
  #       run: df -h
  # self-host-test:
  #   name: self-hosted test
  #   runs-on: [self-hosted, edge, jammy]
  #   steps:
  #     - run: echo hello
  #     - run: df -h
      # - uses: actions/checkout@v4.1.1
      # - uses: canonical/setup-lxd@v0.1.1
      # - name: Pack charm
      #   run: |
      #     sudo snap install charmcraft --classic --channel latest/stable
      #     charmcraft pack -v
      # - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs >> rustup.sh
      # - run: sh rustup.sh -y
      # - run: $HOME/.cargo/bin/cargo install ripgrep
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     limit-access-to-actor: true
