name: Manual test

on:
  # push:
  # pull_request:
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: [self-hosted, github-runner]
    steps:
      - name: Echo
        run: echo "Hello push"
