name: Manual test

on:
  # push:
  pull_request:
  workflow_dispatch:

jobs:
  # github-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Echo test
  #       run: echo hello
  #     - name: Disk usage
  #       run: df -h
  self-host-test:
    name: self-hosted test
    runs-on: [self-hosted, large]
    steps:
      - name: Echo test
        run: echo hello
      - name: Disk usage
        run: df -h
      - name: Echo env var
        run: echo $DOCKERHUB_MIRROR
      - name: Setup operator environment
        uses: yhaliaw/actions-operator@microk8s-docker-registry
        with:
          provider: microk8s
          microk8s-docker-registry: https://github-runner-dockerhub-cache.canonical.com:5000
      - name: Wait
        run: sleep 60m
      # - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs >> rustup.sh
      # - run: sh rustup.sh -y
      # - run: $HOME/.cargo/bin/cargo install ripgrep
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     limit-access-to-actor: true
