name: Microstack Test

on:
  push:

jobs:
    test:
        runs-on: [self-hosted, linux, x64, two-xlarge]
        steps:
          - run: |
              sudo snap install openstack --channel 2023.1
              sunbeam prepare-node-script | bash -x && newgrp snap_daemon
              sunbeam cluster bootstrap --accept-defaults
              sunbeam configure --accept-defaults --openrc demo-openrc
              sunbeam openrc > admin-openrc
              . admin-openrc
              openstack user list
