name: Microstack Test

on:
  push:

jobs:
    test:
        runs-on: [self-hosted, linux, x64, xlarge]
        steps:
          - run: sudo snap install openstack --channel 2023.1
          - run: sunbeam prepare-node-script | bash -x && newgrp snap_daemon
          - run: sunbeam cluster bootstrap --accept-defaults
          - run: sunbeam configure --accept-defaults --openrc demo-openrc
          - run: sunbeam openrc > admin-openrc
          - run: . admin-openrc
          - run: openstack user list
