name: Promote charm

on:
  workflow_dispatch:
    inputs:
      origin-channel:
        type: choice
        description: "Origin Channel"
        options:
          - latest/edge
      destination-channel:
        type: choice
        description: "Destination Channel"
        options:
          - latest/stable
    secrets:
      CHARMHUB_TOKEN:
        required: false

jobs:
  test-workflow-dispatch:
    runs-on: [self-hosted, runner]
    steps:
      - run: echo "TEST PASS"
