#
# On pull request workflow for ROCKs on self-hosted Github runners
# - Build ROCK
# - Scan using Trivy scanner
# - Upload scan report
#
name: On pull request self-hosted

on:
  pull_request:

jobs:
  build-scan-rocks:
    name: Build and scan ROCKs self-hosted
    runs-on: [self-hosted, linux, X64, jammy, xlarge]
    # long timeout ensures heavy ROCKs have enoguh time to finish build/pack
    timeout-minutes: 2400
    steps:
      - name: Setup LXD
        run: |
          sudo lxd waitready || true
          sudo lxd init --minimal
          sudo chmod a+wr /var/snap/lxd/common/lxd/unix.socket
          lxc network set lxdbr0 ipv6.address none
          bash -c 'sudo usermod -a -G lxd $USER'
          sudo iptables -I DOCKER-USER -j ACCEPT
          sleep 60
      - run: |
          sudo su $USER
          lxc monitor
