name: Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, large]
    steps:
      - uses: canonical/craft-actions/rockcraft-pack@main
        with:
          path: mlserver-huggingface
          verbosity: trace
      - run: sleep 10000
