#
# On pull request workflow for ROCKs on self-hosted Github runners
# - Build ROCK
# - Scan using Trivy scanner
# - Upload scan report
#
name: On pull request self-hosted

on:
  pull_request:

jobs:
  build-scan-rocks:
    name: Build and scan ROCKs self-hosted
    runs-on: [self-hosted, linux, X64, jammy, xlarge]
    # long timeout ensures heavy ROCKs have enoguh time to finish build/pack
    timeout-minutes: 2400
    strategy:
      matrix:
        rock:
          - mlserver-huggingface
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          repository: canonical/seldonio-rocks

      - name: Install tools
        run: |
          sudo apt-get update -yqq
          sudo apt install strace -yqq
      - name: Setup LXD
        run: |
          sudo lxd waitready || true
          sudo lxd init --minimal
          sudo chmod a+wr /var/snap/lxd/common/lxd/unix.socket
          lxc network set lxdbr0 ipv6.address none
          sudo bash -c "echo 127.0.0.1 $(cat /etc/hostname) >> /etc/hosts"
          bash -c 'sudo usermod -a -G lxd $USER'
          sudo iptables -I DOCKER-USER -j ACCEPT
      - run: |
          sudo su $USER
      - run: |
          lxc image export ubuntu:22.04 test
      - name: snap logs
        if: always()
        run: |
          cat /etc/hosts