name: Tests

on:
  pull_request:

jobs:
  test-run:
    name: Test job pickup
    runs-on: [self-hosted, ARM64, stg-private-endpoint]
    steps:
      - name: echo hello world
        run: |
          echo hello world
