name: Manual Test Env

on:
  pull_request:

jobs:
    manual-test-env:
      name: manual test env
      runs-on: ['self-hosted', 'xlarge']
      timeout-minutes: 2100
      steps:
      - name: Remove Android SDK
        run: sudo rm -rf /usr/local/lib/android
      - uses: actions/checkout@v4.1.1
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          channel: 1.26-strict/stable
          microk8s-addons: "dns ingress hostpath-storage" 
          juju-channel: 3.2/stable
      - name: Run pre-run scripts
        run: bash -xe scripts/setup-microstack.sh
      - name: Tmate debugging session (self-hosted)
        uses: canonical/action-tmate@main
        timeout-minutes: 1800
